language: java

cache:
  directories:
  - $HOME/.m2
  
matrix:
  include:
    - jdk: oraclejdk8
    - sudo: false
      dist: trusty
      jdk: oraclejdk9

before_install:
  - export MAVEN_SKIP_RC=true